### PR TITLE
Added Simulation Demonstration notebook to documentation.

### PR DESCRIPTION
**Pull request by boryana-ilieva**

### CODE REVIEW

**Comment by peisenha** [comment]
How should we think about it being integrated in the doc? Maybe just a link somwhere to a mybinder notebook?

(base) peisenha@pontos:~/.../soepy/doc$ make html
Running Sphinx v1.7.9
loading pickled environment... done
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 5 source files that are out of date
updating environment: [extensions changed] 5 added, 0 changed, 0 removed
reading sources... [100%] mathematical_model                                                                                                                                                                                                                                       
/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/soepy/doc/source/data_frame_sim_test_analysis.ipynb: WARNING: document not readable. Ignored.
/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/soepy/doc/source/index.rst:9: WARNING: toctree contains reference to nonexisting document 'data_frame_sim_test_analysis'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] mathematical_model                                                                                                                                                                                                                                        
generating indices... genindex
writing additional pages... search
copying images... [100%] images/algorithm.png                                                                                                                                                                                                                                      
copying static files... WARNING: html_static_path entry '/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/soepy/doc/source/.static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in build/html.

**Comment by boryana-ilieva** [comment]
I was thinking that, for now, the simplest thing would be to have the notebook with the simulated data frame as a section of the documentation -- Simulation Documentation. Anne is currently working on preparing some data for us and seeing the data frame in this way is simple and helpful for her.

I was thinking of doing some more complex (and better) integration with a tutorial and a simulation example in the future.

**Comment by boryana-ilieva** [comment]
@peisenha , added the needed sphinx extension, (nbsphinx) to requirements. You can try wether the notebook gets generated as a chapter of the html docs on your machine now!

**Comment by peisenha** [comment]
@boryana-ilieva , please always make sure that TRAVIS is running properly. @SeBecker will be glad to help if needed.

**Comment by peisenha** [comment]
@boryana-ilieva , let me know if this if finished on your end as well. Then I will merge it in master.

**Comment by boryana-ilieva** [comment]
@peisenha, yes is finished, please do merge.

**Pull request merged**
